# Generated by Django 5.1.3 on 2025-04-14 08:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_api', '0021_customercontact_email_customercontact_mobile_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Option',
                'verbose_name_plural': 'Delivery Options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OtherOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Other Option',
                'verbose_name_plural': 'Other Options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTermOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Term Option',
                'verbose_name_plural': 'Payment Term Options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TermCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Term/Condition',
                'verbose_name_plural': 'Terms & Conditions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('for_approval', 'For Approval'), ('approved', 'Approved'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('purchase_request', models.TextField(blank=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('RMB', 'Chinese Yuan'), ('PHP', 'Philippine Peso')], default='PHP', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('price_validity', models.CharField(blank=True, max_length=255)),
                ('validity_period', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='admin_api.customer')),
                ('customer_contacts', models.ManyToManyField(blank=True, related_name='quotations', to='admin_api.customercontact')),
                ('delivery_options', models.ManyToManyField(blank=True, related_name='quotations', to='quotations_api.deliveryoption')),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_quotations', to=settings.AUTH_USER_MODEL)),
                ('other_options', models.ManyToManyField(blank=True, related_name='quotations', to='quotations_api.otheroption')),
                ('payment_terms', models.ManyToManyField(blank=True, related_name='quotations', to='quotations_api.paymenttermoption')),
                ('terms_conditions', models.ManyToManyField(blank=True, related_name='quotations', to='quotations_api.termcondition')),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'ordering': ['-created_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationAdditionalControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_carton_packing', models.BooleanField(default=False)),
                ('do_not_show_all_photos', models.BooleanField(default=False)),
                ('highlight_item_notes', models.BooleanField(default=False)),
                ('show_devaluation_clause', models.BooleanField(default=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_controls', to='quotations_api.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quotation_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quotations_api.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='LastQuotedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_quoted_date', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_quoted_prices_received', to='admin_api.customer')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_quoted_prices', to='admin_api.inventory')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_prices_history', to='quotations_api.quotation')),
            ],
            options={
                'verbose_name': 'Last Quoted Price',
                'verbose_name_plural': 'Last Quoted Prices',
                'ordering': ['-last_quoted_date'],
                'unique_together': {('inventory', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(editable=False, max_length=50)),
                ('brand_name', models.CharField(editable=False, max_length=100)),
                ('show_brand', models.BooleanField(default=True)),
                ('made_in', models.TextField(blank=True, editable=False, null=True)),
                ('show_made_in', models.BooleanField(default=True)),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='quotation_item_photos/')),
                ('show_photo', models.BooleanField(default=True)),
                ('external_description', models.TextField(blank=True)),
                ('actual_landed_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_landed_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('baseline_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('has_discount', models.BooleanField(default=False)),
                ('discount_type', models.CharField(blank=True, choices=[('value', 'Value'), ('percentage', 'Percentage')], max_length=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='admin_api.inventory')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations_api.quotation')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('quotation', 'inventory')},
            },
        ),
        migrations.CreateModel(
            name='QuotationSalesAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'Main'), ('support', 'Support')], default='support', max_length=10)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_assignments', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_agents', to='quotations_api.quotation')),
            ],
            options={
                'ordering': ['role', 'agent__username'],
                'unique_together': {('quotation', 'agent')},
            },
        ),
    ]
