# Generated by Django 5.1.3 on 2025-04-16 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_api', '0021_customercontact_email_customercontact_mobile_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('for_approval', 'For Approval'), ('approved', 'Approved'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('purchase_request', models.TextField(blank=True)),
                ('expiry_date', models.DateField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EURO', 'EURO'), ('RMB', 'RMB'), ('PHP', 'PHP')], max_length=4)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='admin_api.customer')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'quote_number'],
            },
        ),
        migrations.CreateModel(
            name='QuotationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quotation_attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quotations_api.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationSalesAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('main', 'Main'), ('support', 'Support')], max_length=10)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_agents', to='quotations_api.quotation')),
            ],
            options={
                'ordering': ['role', 'agent_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('role', 'main')), fields=('quotation', 'role'), name='unique_main_agent_per_quotation')],
            },
        ),
    ]
