# Generated by Django 5.1.3 on 2025-04-19 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationAdditionalControls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_carton_packing', models.BooleanField(default=True)),
                ('do_not_show_all_photos', models.BooleanField(default=True)),
                ('highlight_item_notes', models.BooleanField(default=True)),
                ('show_devaluation_clause', models.BooleanField(default=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_controls', to='quotations_api.quotation')),
            ],
        ),
    ]
