# Generated by Django 5.1.3 on 2025-04-15 08:55

import django.db.models.deletion
import quotations_api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0021_customercontact_email_customercontact_mobile_number_and_more'),
        ('quotations_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Payment Term',
                'verbose_name_plural': 'Payment Terms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TermsCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Terms & Condition',
                'verbose_name_plural': 'Terms & Conditions',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='quotationadditionalcontrol',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='terms_conditions',
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-created_on'], 'verbose_name': 'Quotation', 'verbose_name_plural': 'Quotations'},
        ),
        migrations.AlterModelOptions(
            name='quotationattachment',
            options={'ordering': ['-uploaded_on'], 'verbose_name': 'Quotation Attachment', 'verbose_name_plural': 'Quotation Attachments'},
        ),
        migrations.AlterModelOptions(
            name='quotationitem',
            options={'ordering': ['id'], 'verbose_name': 'Quotation Item', 'verbose_name_plural': 'Quotation Items'},
        ),
        migrations.AlterModelOptions(
            name='quotationsalesagent',
            options={'ordering': ['role', 'agent__username'], 'verbose_name': 'Quotation Sales Agent', 'verbose_name_plural': 'Quotation Sales Agents'},
        ),
        migrations.RenameField(
            model_name='quotationattachment',
            old_name='uploaded_at',
            new_name='uploaded_on',
        ),
        migrations.AlterUniqueTogether(
            name='quotationitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='deliveryoption',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deliveryoption',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='otheroption',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='otheroption',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='price_validity',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='validity_period',
        ),
        migrations.AddField(
            model_name='quotation',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='validity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_quotation_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_api.brand'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='net_selling',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='total_selling',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('euro', 'EURO'), ('rmb', 'RMB'), ('php', 'PHP')], default='usd', max_length=5),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='delivery_options',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='other_options',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='purchase_request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='quotationattachment',
            name='file',
            field=models.FileField(upload_to=quotations_api.models.quotation_attachment_path),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='actual_landed_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='estimated_landed_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='external_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='quotationsalesagent',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuotationAdditionalControls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_carton_packing', models.BooleanField(default=True)),
                ('do_not_show_all_photos', models.BooleanField(default=False)),
                ('highlight_item_notes', models.BooleanField(default=False)),
                ('show_devaluation_clause', models.BooleanField(default=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_controls', to='quotations_api.quotation')),
            ],
            options={
                'verbose_name': 'Quotation Additional Controls',
                'verbose_name_plural': 'Quotation Additional Controls',
            },
        ),
        migrations.DeleteModel(
            name='PaymentTermOption',
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='quotations_api.paymentterm'),
        ),
        migrations.DeleteModel(
            name='QuotationAdditionalControl',
        ),
        migrations.DeleteModel(
            name='TermCondition',
        ),
        migrations.AddField(
            model_name='quotation',
            name='terms_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='quotations_api.termscondition'),
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='made_in',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='show_made_in',
        ),
        migrations.AddField(
            model_name='quotation',
            name='delivery_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='quotations_api.deliveryoption'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='other_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='quotations_api.otheroption'),
        ),
    ]
