# Generated by Django 5.1.3 on 2025-04-20 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0021_customercontact_email_customercontact_mobile_number_and_more'),
        ('quotations_api', '0003_delivery_other_payment_quotationtermsandconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_contacts', to='admin_api.customercontact')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='quotations_api.quotation')),
            ],
            options={
                'ordering': ['customer_contact__contact_person'],
            },
        ),
    ]
