# Generated by Django 5.1.3 on 2025-04-20 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0021_customercontact_email_customercontact_mobile_number_and_more'),
        ('quotations_api', '0004_quotationcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='quotation_item_photos/')),
                ('external_description', models.TextField(blank=True)),
                ('show_brand', models.BooleanField(default=True)),
                ('show_made_in', models.BooleanField(default=True)),
                ('actual_landed_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_landed_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('show_photo', models.BooleanField(default=True)),
                ('baseline_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('has_discount', models.BooleanField(default=False)),
                ('discount_type', models.CharField(choices=[('value', 'Value'), ('percentage', 'Percentage')], default='percentage', max_length=10)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('landed_cost_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_selling', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_selling', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_api.inventory')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations_api.quotation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LastQuotedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quoted_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.customer')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.inventory')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations_api.quotation')),
            ],
            options={
                'ordering': ['-quoted_at'],
                'unique_together': {('inventory', 'customer')},
            },
        ),
    ]
