# Generated by Django 5.1.3 on 2025-05-23 09:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_api', '0027_alter_customuser_user_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('supplier_type', models.CharField(choices=[('local', 'Local'), ('foreign', 'Foreign')], max_length=10)),
                ('delivery_terms', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EURO'), ('RMB', 'RMB'), ('PHP', 'PHP')], max_length=4)),
                ('supplier_address', models.TextField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('items_gross_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('items_total_discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('order_level_discount_charge_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('grand_total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('po_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='admin_api.supplier')),
            ],
            options={
                'ordering': ['-po_date', '-po_number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderDiscountCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('is_percentage', models.BooleanField(default=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_deduction', models.BooleanField(default=False)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts_charges', to='purchase_order_api.purchaseorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=15, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('calculated_discount_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_items', to='admin_api.inventory')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_order_api.purchaseorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderPaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_terms_description', models.CharField(max_length=255)),
                ('dp_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('terms_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_term', to='purchase_order_api.purchaseorder')),
            ],
        ),
    ]
