# Generated by Django 5.1.3 on 2025-05-26 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_api', '0002_alter_purchaseorderitem_discount_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=True)),
                ('task', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_po_steps', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_steps', to='purchase_order_api.purchaseorder')),
            ],
            options={
                'ordering': ['purchase_order', 'step'],
                'unique_together': {('purchase_order', 'step')},
            },
        ),
    ]
