# Generated by Django 5.1.3 on 2025-05-28 15:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_api', '0003_purchaseorderroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderroute',
            name='access',
            field=models.CharField(choices=[('inventory', 'Inventory'), ('quotations', 'Quotations'), ('reservation_slips', 'Reservation Slips'), ('sales_orders', 'Sales Orders'), ('accounting_aging_reports', 'Accounting Aging Reports'), ('accounting_account_receivables', 'Accounting Account Receivables'), ('accounting_workstreams', 'Accounting Workstreams'), ('importation', 'Importation'), ('delivery', 'Delivery'), ('warehouse_inbound', 'Warehouse Inbound'), ('warehouse_delivery', 'Warehouse Delivery'), ('warehouse_audit', 'Warehouse Audit'), ('shipments', 'Shipments'), ('calendar', 'Calendar'), ('purchase_orders', 'Purchase Orders')], default='purchase_orders', help_text='User role/permission required to complete this step', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseorderroute',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('supervisor', 'Supervisor')], max_length=20), default=['admin', 'supervisor'], help_text='User roles that can complete this step', size=None),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending PO Approval'), ('for_dp', 'For Down Payment'), ('pending_dp_approval', 'Pending DP Approval'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='PurchaseOrderDownPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_slip', models.FileField(blank=True, null=True, upload_to='po_payment_slips/')),
                ('remarks', models.TextField(blank=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='down_payments', to='purchase_order_api.purchaseorder')),
            ],
        ),
    ]
