# Generated by Django 5.1.3 on 2025-05-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_api', '0004_purchaseorderroute_access_purchaseorderroute_roles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='expected_delivery_date',
            new_name='ready_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='expected_delivery_date',
        ),
    ]
