# Generated by Django 5.1.3 on 2025-05-29 15:20

import django.contrib.postgres.fields
import purchase_order_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_api', '0005_rename_expected_delivery_date_purchaseorderitem_ready_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='batch_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Batch number for grouping items by ready date', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending PO Approval'), ('for_dp', 'For Down Payment'), ('pending_dp_approval', 'Pending DP Approval'), ('confirm_ready_dates', 'Confirm Ready Dates'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorderroute',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('supervisor', 'Supervisor')], max_length=20), default=purchase_order_api.models.default_roles, help_text='User roles that can complete this step', size=None),
        ),
    ]
