# Generated by Django 5.1.3 on 2025-05-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_api', '0006_purchaseorderitem_batch_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending PO Approval'), ('for_dp', 'For Down Payment'), ('pending_dp_approval', 'Pending DP Approval'), ('confirm_ready_dates', 'Confirm Ready Dates'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
