# Generated by Django 5.1.3 on 2025-05-30 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_api', '0007_alter_purchaseorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending PO Approval'), ('for_dp', 'For Down Payment'), ('pending_dp_approval', 'Pending DP Approval'), ('confirm_ready_dates', 'Confirm Ready Dates'), ('packing_list_1', 'Packing List 1'), ('packing_list_2', 'Packing List 2'), ('packing_list_3', 'Packing List 3'), ('approve_for_import_1', 'Approve for Import 1'), ('approve_for_import_2', 'Approve for Import 2'), ('approve_for_import_3', 'Approve for Import 3'), ('payment_1', 'Payment 1'), ('payment_2', 'Payment 2'), ('payment_3', 'Payment 3'), ('invoice_1', 'Invoice 1'), ('invoice_2', 'Invoice 2'), ('invoice_3', 'Invoice 3'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=50),
        ),
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.PositiveSmallIntegerField()),
                ('document', models.FileField(upload_to='invoice_documents/')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_documents', to='purchase_order_api.purchaseorder')),
            ],
            options={
                'ordering': ['purchase_order', 'batch_number'],
                'unique_together': {('purchase_order', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.PositiveSmallIntegerField()),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_packages', models.PositiveIntegerField()),
                ('total_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('document', models.FileField(upload_to='packing_lists/')),
                ('approved', models.BooleanField(default=None, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_lists', to='purchase_order_api.purchaseorder')),
            ],
            options={
                'ordering': ['purchase_order', 'batch_number'],
                'unique_together': {('purchase_order', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='PaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.PositiveSmallIntegerField()),
                ('document', models.FileField(upload_to='payment_documents/')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_documents', to='purchase_order_api.purchaseorder')),
            ],
            options={
                'ordering': ['purchase_order', 'batch_number'],
                'unique_together': {('purchase_order', 'batch_number')},
            },
        ),
    ]
