from django.urls import path
from .views import LoginView, UserView, SidebarView, BrandView, CategoryView, WarehouseView, SupplierView, ParentCompanyView, CustomerView, BrokerView, ForwarderView, InventoryView, InventoryGeneralView, InventoryDescriptionView, CategoryChildrenView, InventoryTemplateView, InventoryUploadView
app_name = 'admin_api'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('sidebar/', SidebarView.as_view(), name='sidebar'),
    path('users/', UserView.as_view(), name='users'),
    path('users/<int:pk>/', UserView.as_view(), name='user-detail'),
    path('brands/', BrandView.as_view(), name='brands'),
    path('brands/<int:pk>/', BrandView.as_view(), name='brand-detail'),
    path('categories/', CategoryView.as_view(), name='categories'),
    path('categories/<int:pk>/', CategoryView.as_view(), name='category-detail'),
    path('categories/<int:parent_id>/children/', CategoryChildrenView.as_view(), name='category-children'),
    path('warehouses/', WarehouseView.as_view(), name='warehouses'),
    path('warehouses/<int:pk>/', WarehouseView.as_view(), name='warehouse-detail'),
    path('suppliers/', SupplierView.as_view(), name='suppliers'),
    path('suppliers/<int:pk>/', SupplierView.as_view(), name='supplier-detail'),
    path('parent-companies/', ParentCompanyView.as_view(), name='parent-companies'),
    path('parent-companies/<int:pk>/', ParentCompanyView.as_view(), name='parent-company-detail'),
    path('customers/', CustomerView.as_view(), name='customers'),
    path('customers/<int:pk>/', CustomerView.as_view(), name='customer-detail'),
    path('brokers/', BrokerView.as_view(), name='brokers'),
    path('brokers/<int:pk>/', BrokerView.as_view(), name='broker-detail'),
    path('forwarders/', ForwarderView.as_view(), name='forwarders'),
    path('forwarders/<int:pk>/', ForwarderView.as_view(), name='forwarder-detail'),
    path('inventory/', InventoryView.as_view(), name='inventory-list'),
    path('inventory/<int:pk>/', InventoryView.as_view(), name='inventory-detail'),
    path('inventory/general/', InventoryGeneralView.as_view(), name='inventory-general-create'),
    path('inventory/<int:pk>/general/', InventoryGeneralView.as_view(), name='inventory-general-update'),
    path('inventory/<int:pk>/description/', InventoryDescriptionView.as_view(), name='inventory-description-update'),
    path('inventory/download-template/', InventoryTemplateView.as_view(), name='inventory-download-template'),
    path('inventory/upload/', InventoryUploadView.as_view(), name='inventory-upload'),
]