# Generated by Django 5.1.3 on 2025-03-06 15:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('made_in', models.TextField(blank=True, null=True)),
                ('show_made_in', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('inventory', 'Inventory'), ('quotations', 'Quotations'), ('sales_orders', 'Sales_orders'), ('importation', 'Importation'), ('warehouse', 'Warehouse'), ('delivery', 'Delivery'), ('payment', 'Payment'), ('customers', 'Customers'), ('sampling', 'Sampling')], max_length=20), blank=True, default=list, size=None),
        ),
    ]
