# Generated by Django 5.1.3 on 2025-03-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0003_alter_customuser_role_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='remarks',
        ),
    ]
