# Generated by Django 5.1.3 on 2025-03-09 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0005_warehouse_shelf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registered_name', models.CharField(max_length=100)),
                ('supplier_type', models.CharField(choices=[('local', 'Local'), ('foreign', 'Foreign')], max_length=10)),
                ('currency', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('inco_terms', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'registered_name')},
            },
        ),
        migrations.CreateModel(
            name='SupplierAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='admin_api.supplier')),
            ],
            options={
                'verbose_name_plural': 'supplier addresses',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='admin_api.supplier')),
            ],
            options={
                'ordering': ['contact_person'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stock_payment_terms', models.CharField(max_length=100)),
                ('stock_dp_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock_terms_days', models.PositiveIntegerField()),
                ('import_payment_terms', models.CharField(max_length=100)),
                ('import_dp_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('import_terms_days', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_term', to='admin_api.supplier')),
            ],
        ),
    ]
