# Generated by Django 5.1.3 on 2025-03-10 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0006_supplier_supplieraddress_suppliercontact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('consolidate_payment_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'parent companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_set', to='admin_api.parentcompany')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParentCompanyPaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_payment_terms', models.CharField(max_length=100)),
                ('stock_dp_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock_terms_days', models.PositiveIntegerField()),
                ('import_payment_terms', models.CharField(max_length=100)),
                ('import_dp_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('import_terms_days', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_term', to='admin_api.parentcompany')),
            ],
        ),
    ]
