# Generated by Django 5.1.3 on 2025-03-10 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0007_parentcompany_customer_parentcompanypaymentterm'),
    ]

    operations = [
        # First add all fields
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Quezon City', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='company_address',
            field=models.TextField(default='Quezon City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='has_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='registered_name',
            field=models.CharField(default='Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='tin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='vat_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField()),
                ('delivery_schedule', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='admin_api.customer')),
            ],
            options={
                'verbose_name_plural': 'customer addresses',
                'ordering': ['delivery_address'],
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='admin_api.customer')),
            ],
            options={
                'ordering': ['contact_person'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stock_payment_terms', models.CharField(max_length=100)),
                ('stock_dp_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock_terms_days', models.PositiveIntegerField()),
                ('import_payment_terms', models.CharField(max_length=100)),
                ('import_dp_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('import_terms_days', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_term', to='admin_api.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        # Add unique constraint LAST, after all fields are created
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('name', 'registered_name')},
        ),
    ]