# Generated by Django 5.1.3 on 2025-03-11 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0008_alter_customer_unique_together_customer_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('payment_type', models.CharField(choices=[('cod', 'COD'), ('terms', 'Payment Terms')], default='cod', max_length=10)),
                ('payment_terms_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'broker',
                'verbose_name_plural': 'brokers',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='BrokerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('office_number', models.CharField(max_length=20)),
                ('personal_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='admin_api.broker')),
            ],
            options={
                'verbose_name': 'broker contact',
                'verbose_name_plural': 'broker contacts',
                'ordering': ['contact_person'],
            },
        ),
    ]
