# Generated by Django 5.1.3 on 2025-03-11 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0009_broker_brokercontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forwarder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('payment_type', models.CharField(choices=[('cod', 'COD'), ('terms', 'Payment Terms')], default='cod', max_length=10)),
                ('payment_terms_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'forwarder',
                'verbose_name_plural': 'forwarders',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='ForwarderContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('office_number', models.CharField(max_length=20)),
                ('personal_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forwarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='admin_api.forwarder')),
            ],
            options={
                'verbose_name': 'forwarder contact',
                'verbose_name_plural': 'forwarder contacts',
                'ordering': ['contact_person'],
            },
        ),
    ]
