# Generated by Django 5.1.3 on 2025-03-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0011_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inventory',
            name='external_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='height_unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='inventory',
            name='landed_cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='landed_cost_unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inventory',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='length_unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='inventory',
            name='list_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='list_price_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='inventory',
            name='materials',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='packaging_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='packaging_package',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='packaging_units',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inventory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_photos/'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inventory',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='volume_unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='inventory',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='width_unit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
