# Generated by Django 5.1.3 on 2025-03-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0012_inventory_color_inventory_external_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='features',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='package_includes',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='warranty',
        ),
    ]
