# Generated by Django 5.1.3 on 2025-03-14 14:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0013_remove_inventory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('users', 'Users'), ('brands', 'Brands'), ('brokers', 'Brokers'), ('categories', 'Categories'), ('forwarders', 'Forwarders'), ('inventory', 'Inventory'), ('parent_companies', 'Parent_companies'), ('suppliers', 'Suppliers'), ('warehouses', 'Warehouses')], max_length=20), blank=True, default=list, size=None),
        ),
    ]
