# Generated by Django 5.1.3 on 2025-03-14 17:49

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0016_recreate_shelf_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='admin_access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('users', 'Users'), ('brands', 'Brands'), ('brokers', 'Brokers'), ('categories', 'Categories'), ('customers', 'Customers'), ('forwarders', 'Forwarders'), ('inventory', 'Inventory'), ('parent_companies', 'Parent_companies'), ('suppliers', 'Suppliers'), ('warehouses', 'Warehouses')], max_length=20), blank=True, default=list, size=None),
        ),
        migrations.CreateModel(
            name='SupplierBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_address', models.TextField()),
                ('account_number', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=3)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('swift_code', models.CharField(max_length=20)),
                ('intermediary_bank', models.CharField(blank=True, max_length=100)),
                ('intermediary_swift_name', models.CharField(blank=True, max_length=100)),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('beneficiary_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='admin_api.supplier')),
            ],
            options={
                'verbose_name_plural': 'supplier banks',
                'ordering': ['bank_name'],
            },
        ),
    ]
