# Generated by Django 5.1.3 on 2025-03-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0017_alter_customuser_admin_access_supplierbank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='inco_terms',
            new_name='delivery_terms',
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='inventory',
            name='audit_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='available_for_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='incoming_pending_po',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='incoming_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reserved_pending_so',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='stock_on_hand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_expected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_tagging',
            field=models.CharField(choices=[('never_sold', 'Never Sold'), ('discontinued', 'Discontinued'), ('dormant', 'Dormant'), ('none', 'None')], default='never_sold', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EURO', 'EURO'), ('RMB', 'RMB'), ('PHP', 'PHP')], max_length=4),
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='registered_name',
        ),
    ]
