# Generated by Django 5.1.3 on 2025-03-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0018_rename_inco_terms_supplier_delivery_terms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierpaymentterm',
            old_name='import_dp_percentage',
            new_name='dp_percentage',
        ),
        migrations.RenameField(
            model_name='supplierpaymentterm',
            old_name='import_payment_terms',
            new_name='payment_terms',
        ),
        migrations.RenameField(
            model_name='supplierpaymentterm',
            old_name='import_terms_days',
            new_name='terms_days',
        ),
        migrations.RemoveField(
            model_name='supplierpaymentterm',
            name='stock_dp_percentage',
        ),
        migrations.RemoveField(
            model_name='supplierpaymentterm',
            name='stock_payment_terms',
        ),
        migrations.RemoveField(
            model_name='supplierpaymentterm',
            name='stock_terms_days',
        ),
    ]
