# Generated by Django 5.1.3 on 2025-03-29 03:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0019_rename_import_dp_percentage_supplierpaymentterm_dp_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='admin_access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('users', 'Users'), ('brands', 'Brands'), ('brokers', 'Brokers'), ('categories', 'Categories'), ('customers', 'Customers'), ('forwarders', 'Forwarders'), ('inventory', 'Inventory'), ('parent_companies', 'Parent_companies'), ('suppliers', 'Suppliers'), ('warehouses', 'Warehouses')], max_length=40), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('inventory', 'Inventory'), ('quotations', 'Quotations'), ('reservation_slips', 'Reservation_slips'), ('sales_orders', 'Sales_orders'), ('accounting_aging_reports', 'Accounting_aging_reports'), ('accounting_account_receivables', 'Accounting_account_receivables'), ('accounting_workstreams', 'Accounting_workstreams'), ('importation', 'Importation'), ('delivery', 'Delivery'), ('warehouse_inbound', 'Warehouse_inbound'), ('warehouse_delivery', 'Warehouse_delivery'), ('warehouse_audit', 'Warehouse_audit'), ('shipments', 'Shipments'), ('calendar', 'Calendar')], max_length=40), blank=True, default=list, size=None),
        ),
    ]
