# Generated by Django 5.1.3 on 2025-04-27 14:55

from django.db import migrations, models
import uuid

def generate_unique_cip_codes(apps, schema_editor):
    Inventory = apps.get_model('admin_api', 'Inventory')
    for inventory in Inventory.objects.all():
        inventory.cip_code = f"CIP-{uuid.uuid4().hex[:8].upper()}"
        inventory.save()

class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0021_customercontact_email_customercontact_mobile_number_and_more'),
    ]

    operations = [
        # First add the field with null=True to avoid immediate validation
        migrations.AddField(
            model_name='inventory',
            name='cip_code',
            field=models.CharField(max_length=50, null=True),
        ),
        
        # Run the function to populate with unique values
        migrations.RunPython(generate_unique_cip_codes),
        
        # Then make it non-nullable and unique
        migrations.AlterField(
            model_name='inventory',
            name='cip_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]