# Generated by Django 5.1.3 on 2025-05-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0022_inventory_cip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='pattern',
            field=models.TextField(blank=True),
        ),
    ]
