# Generated by Django 5.1.3 on 2025-05-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0024_alter_brokercontact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcompanypaymentterm',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
