# Generated by Django 5.1.3 on 2025-05-23 09:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0026_supplieraddress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('inventory', 'Inventory'), ('quotations', 'Quotations'), ('reservation_slips', 'Reservation_slips'), ('sales_orders', 'Sales_orders'), ('accounting_aging_reports', 'Accounting_aging_reports'), ('accounting_account_receivables', 'Accounting_account_receivables'), ('accounting_workstreams', 'Accounting_workstreams'), ('importation', 'Importation'), ('delivery', 'Delivery'), ('warehouse_inbound', 'Warehouse_inbound'), ('warehouse_delivery', 'Warehouse_delivery'), ('warehouse_audit', 'Warehouse_audit'), ('shipments', 'Shipments'), ('calendar', 'Calendar'), ('purchase_orders', 'Purchase_orders')], max_length=40), blank=True, default=list, size=None),
        ),
    ]
