# Generated by Django 5.1.3 on 2025-06-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0027_alter_customuser_user_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('CNY', 'Chinese Yuan')], max_length=3, unique=True)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_exchange_rates',
                'ordering': ['-updated_at'],
            },
        ),
    ]
